// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/sa-reset-dialog copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDia: typeof import('element-plus/es')['ElDia']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaArea: typeof import('./src/components/sa-area.vue')['default']
    SaEnhanBtnAdd: typeof import('./src/components/sa-enhan-btn-add.vue')['default']
    SaEnhanBtnRemoveAll: typeof import('./src/components/sa-enhan-btn-remove-all.vue')['default']
    SaEnhanCard: typeof import('./src/components/sa-enhan-card.vue')['default']
    SaHelpDialog: typeof import('./src/components/sa-help-dialog.vue')['default']
    SaMenu: typeof import('./src/components/sa-menu.vue')['default']
    SaPlayer: typeof import('./src/components/sa-player.vue')['default']
    SaResetDialog: typeof import('./src/components/sa-reset-dialog.vue')['default']
    SaTokenTip: typeof import('./src/components/sa-token-tip.vue')['default']
  }
}
